name = "Strata"
version = "0.1.0"
defaultTargets = ["Strata", "StrataMain", "StrataVerify", "StrataToCBMC"]
testDriver = "StrataTest"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible.git"
rev = "b949552f6ca8e223f424b3e3b33f74185bbf1179"

[[lean_lib]]
name = "Strata"

[[lean_exe]]
name = "strata"
root = "StrataMain"

[[lean_lib]]
name = "StrataExamples"
globs = ["Examples.Lean.+"]

[[lean_lib]]
name = "StrataTest"
globs = ["StrataTest.+"]

[[lean_exe]]
name = "StrataVerify"

[[lean_exe]]
name = "StrataToCBMC"

[[lean_exe]]
name = "BoogieToGoto"