name = "StrataDoc"
defaultTargets = ["ddm", "langdef", "laurel"]

[[require]]
name = "Strata"
path = "../.."

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.27.0"

[[lean_lib]]
name = "DDMDoc"

[[lean_lib]]
name = "LangDefDoc"

[[lean_exe]]
name = "ddm"
root = "DDMDocMain"

[[lean_exe]]
name = "langdef"
root = "LangDefDocMain"

[[lean_lib]]
name = "LaurelDoc"

[[lean_exe]]
name = "laurel"
root = "LaurelDocMain"
